import type { RepoContext, Rule } from "./types.js";

const CATEGORY_ORDER = [
  "security",
  "architecture",
  "performance",
  "testing",
  "process",
  "style",
  "other",
] as const;

export interface SkillRender {
  /** Kebab-case skill folder name, e.g. "commander-js-review-conventions". */
  folderName: string;
  /** SKILL.md content. */
  content: string;
  /** Rules included after filtering. */
  included: number;
  excludedGeneric: number;
}

function slug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Render mined rules as a Claude Code skill folder (see exporters skill).
 * MVP approval note: there is no approval workflow yet, so this renders candidate
 * rules — the human review of the generated file before committing IS the approval
 * step. Generic-specificity rules are excluded by default (an AI assistant already
 * knows them); pass includeGeneric to keep them.
 */
export function renderClaudeSkill(
  context: RepoContext,
  rules: Rule[],
  options: { includeGeneric?: boolean } = {},
): SkillRender {
  const included = options.includeGeneric
    ? rules
    : rules.filter((r) => r.specificity !== "generic");
  const excludedGeneric = rules.length - included.length;
  const repo = `${context.owner}/${context.name}`;
  const folderName = `${slug(context.name)}-review-conventions`;

  const lines: string[] = [
    "---",
    `name: ${folderName}`,
    `description: Engineering conventions mined from ${repo} pull-request review history. Apply when writing, changing, or reviewing code in this repository so new code follows the team's actual review standards.`,
    "---",
    "",
    `# ${context.name} — review conventions`,
    "",
    `Rules below were extracted from real review feedback in ${repo}` +
      ` (generated by RepoMind; evidence links point to the original discussions).`,
    "",
  ];

  for (const category of CATEGORY_ORDER) {
    const categoryRules = included
      .filter((r) => r.category === category)
      .sort((a, b) => b.occurrences - a.occurrences || b.confidence - a.confidence);
    if (categoryRules.length === 0) continue;

    lines.push(`## ${category[0]?.toUpperCase()}${category.slice(1)}`, "");
    for (const rule of categoryRules) {
      const example = rule.evidence[0];
      const receipt = example
        ? ` _(seen in ${rule.occurrences} PR(s), ${rule.reviewerCount} reviewer(s) — [example](${example.commentUrl}))_`
        : "";
      lines.push(`- ${rule.rule}${receipt}`);
    }
    lines.push("");
  }

  return { folderName, content: lines.join("\n"), included: included.length, excludedGeneric };
}
